"""m36_live.py — M3-6 重编译栈序恢复 + autogenerated 标记 真机验收（Blender 5.2.1）。

跑法：blender --background --factory-startup --python m36_live.py

工单验收（M3-6 · spec 级 A/B 的硬前置）：
  * AI 生成的 modifier 打 autogenerated 标记（5.2 modifier 不支持 IDProperty，
    probe 实锤 TypeError → 降级为保留名前缀 `AI_`，可存活 .blend 重载）
  * 重编译只替换标记项、未标记项（艺术家 Subdivision 等）原索引保留
  * 参数重放：已写值回填新 modifier，重编译不重置用户参数
附加（项目纪律）：同 spec 重编译几何零变化（渲染 diff==0）/ 新 spec 结构 diff
  非空 / 反例（SEG_NOT_FOUND、NOT_AUTOGENERATED 标记摘除即接管）/ WAL 留档。
"""
import json
import shutil
import sys
import time
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]  # 仓库根（相对推导，跨机器可移植）

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import bpy

from gn_adapter import GNAdapter
from console import Console

OUT = ROOT / "results"
ROWS: list[dict] = []


def check(name, fn, expect=None):
    try:
        val = fn()
        if expect is not None and val != expect:
            raise AssertionError(f"期望 {expect!r}，实得 {val!r}")
        ROWS.append({"case": name, "ok": True, "detail": str(val)[:140]})
        print(f"  PASS  {name}  {str(val)[:100]}")
    except Exception as exc:  # noqa: BLE001
        ROWS.append({"case": name, "ok": False, "detail": repr(exc)[:200]})
        print(f"  FAIL  {name}  {exc!r}")


def stack_names(obj):
    return [m.name for m in obj.modifiers]


print(f"Blender {bpy.app.version_string}")
ad = GNAdapter(bpy)
bpy.ops.wm.read_factory_settings(use_empty=True)

BODY = {"id": "body", "op": "cylinder", "consumes_input": False,
        "parameters": [
            {"name": "Radius", "type": "FLOAT", "value": 0.04, "min": 0.02, "max": 0.12},
            {"name": "Depth", "type": "FLOAT", "value": 0.095, "min": 0.05, "max": 0.3}]}
CUBE_SPEC = {"id": "body", "op": "cube", "consumes_input": False,
             "parameters": [
                 {"name": "Size", "type": "FLOAT", "value": 0.09, "min": 0.02, "max": 0.12}]}
BITE = {"id": "bite", "op": "sdf_boolean", "consumes_input": True,
        "parameters": [
            {"name": "Voxel_Size", "type": "FLOAT", "value": 0.008,
             "min": 0.001, "max": 0.02}],
        "operand": {"op": "sphere", "radius": 0.03}}

shutil.rmtree(HERE / "_m36_wal", ignore_errors=True)

bpy.ops.mesh.primitive_cube_add()
obj = bpy.context.active_object
obj.name = "MugM36"
obj.data = bpy.data.meshes.new("Base_MugM36")
con = Console(ad, obj, workdir=HERE / "_m36_wal")

print("\n[1] 栈搭建：AI_body → 艺术家 Subsurf（未标记）→ AI_bite")
r = con.compile(dict(BODY))
check("编译 body", lambda: r.ok, True)
sub = obj.modifiers.new("Artist_Subsurf", 'SUBSURF')   # 艺术家手动层（未标记）
r = con.compile(dict(BITE))
check("编译 bite（sdf_boolean）", lambda: r.ok, True)
check("栈序 = [AI_body, Artist_Subsurf, AI_bite]",
      lambda: stack_names(obj), ["AI_body", "Artist_Subsurf", "AI_bite"])
check("AI 产物带标记（AI_ 前缀）",
      lambda: all(n.startswith("AI_") for n in ("AI_body", "AI_bite")), True)
check("艺术家层无标记", lambda: sub.name.startswith("AI_"), False)

print("\n[2] 同 spec 重编译：栈序保留 + 参数重放 + 几何零变化")
con.set_param("body", "Radius", 0.05)                  # 用户已写参数
# bpy_struct 每次访问返回新包装器——对象同一性必须比 DNA 指针（as_pointer）
sub_ptr = sub.as_pointer()
body_ptr_before = con.segments["body"]["mod"].as_pointer()
rd0 = con.render_diff("m36_base")
t0 = time.perf_counter()
r = con.recompile("body")
dt = round((time.perf_counter() - t0) * 1000, 1)
print(f"  recompile body  {dt} ms  {'ok' if r.ok else f'FAIL {r.error}'}")
check("重编译 body ok", lambda: r.ok, True)
check("栈序保留（未标记项原索引不动）",
      lambda: stack_names(obj), ["AI_body", "Artist_Subsurf", "AI_bite"])
check("AI_body 栈位 = 0", lambda: stack_names(obj).index("AI_body"), 0)
check("Artist_Subsurf DNA 指针不变（未被重建）",
      lambda: any(m.as_pointer() == sub_ptr for m in obj.modifiers), True)
check("AI_body 确实被替换（DNA 指针变了）",
      lambda: con.segments["body"]["mod"].as_pointer() != body_ptr_before, True)
check("参数重放 body.Radius=0.05",
      lambda: r.data["reapplied"].get("body.Radius"), 0.05)
sid = con.segments["body"]["sid"]
check("实例输入读回 = 0.05（5.2 properties.inputs 口径）",
      lambda: con.segments["body"]["mod"].properties.inputs[sid["Radius"]]["value"], 0.05)
check("同 spec 指纹一致（结构不变）",
      lambda: con.segments["body"]["fingerprint"] == r.data["fingerprint"], True)
rd1 = con.render_diff("m36_same")
check("同 spec 重编译几何零变化（diff==0）",
      lambda: rd1.data["changed_ratio"], 0.0)

print("\n[3] 新 spec 重编译：结构 diff 非空 + 新参数播种")
r = con.recompile("body", dict(CUBE_SPEC))
print(f"  recompile body→cube  {'ok' if r.ok else f'FAIL {r.error}'}")
check("重编译 body→cube ok", lambda: r.ok, True)
check("gn_delta 非空（结构确实变了）", lambda: bool(r.data["gn_delta"]), True)
check("栈序仍保留（换 spec 也不许重排）",
      lambda: stack_names(obj), ["AI_body", "Artist_Subsurf", "AI_bite"])
check("旧参数 body.Radius 不再重放（新 spec 无此参）",
      lambda: "body.Radius" in r.data["reapplied"], False)
check("新参数 body.Size 播种入账（只补缺口）",
      lambda: con.vparams.get().get("body.Size"), 0.09)
rd2 = con.render_diff("m36_swap")
check("cylinder→cube 渲染 diff 出图（>0）",
      lambda: rd2.data["changed_ratio"] > 0, True)

print("\n[4] 反例（响亮失败，M4-8 结构化）")
r = con.recompile("ghost")
check("不存在段落 → SEG_NOT_FOUND",
      lambda: (r.error or {}).get("error_code"), "SEG_NOT_FOUND")
con.segments["bite"]["mod"].name = "Artist_Bite"       # 摘标记 = 艺术家接管
r = con.recompile("bite")
check("标记摘除 → NOT_AUTOGENERATED 拒绝覆盖",
      lambda: (r.error or {}).get("error_code"), "NOT_AUTOGENERATED")
con.segments["bite"]["mod"].name = "AI_bite"           # 恢复标记
r = con.recompile("bite")
check("标记恢复后重编译放行", lambda: r.ok, True)
check("bite 重编译后栈序完整",
      lambda: stack_names(obj), ["AI_body", "Artist_Subsurf", "AI_bite"])

print("\n[5] WAL 留档 + verifier")
wal_lines = (HERE / "_m36_wal" / "events.jsonl").read_text(encoding="utf-8").splitlines()
rc_events = [json.loads(x) for x in wal_lines if '"recompile"' in x]
check("WAL 有 recompile 事件", lambda: len(rc_events) >= 3, True)
# 栈位序列正是"只动标记项"的机械证据：body@0、body@0、bite@2（各自旧位）
check("WAL 栈位序列 = 各段旧位 [0, 0, 2]",
      lambda: [e.get("payload", {}).get("mod_index") for e in rc_events],
      [0, 0, 2])
check("verifier PASS（重编译后链路健康）", lambda: con.verify("m36").ok, True)

failed = [r for r in ROWS if not r["ok"]]
print(f"\nM3-6 LIVE: {len(ROWS) - len(failed)}/{len(ROWS)} passed")
out = OUT / "m36_result.json"
out.write_text(json.dumps({"rows": ROWS}, ensure_ascii=False, indent=1),
               encoding="utf-8")
print("result ->", out)
sys.exit(1 if failed else 0)
