import bpy
bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.mesh.primitive_cube_add()
o = bpy.context.active_object
m = o.modifiers.new("GN_t", 'NODES')
try:
    m["autogenerated"] = True
    print("SET OK, readback:", m.get("autogenerated"))
    del m["autogenerated"]
    print("DEL OK, readback:", m.get("autogenerated"))
    m["autogenerated"] = True
    print("RESET OK:", m.get("autogenerated"))
except Exception as e:
    print("FAIL:", repr(e))
